#!/usr/bin/with-contenv bash

cat <<EOF
---
Starting linuxserver:swag - ENV based automatic configuration of swag
---
EOF

# Display variables for troubleshooting
echo -e "Variables set:\\n\
AUTO_HOMEASSISTANT=${AUTO_HOMEASSISTANT}\\n\
AUTO_NEXTCLOUD=${AUTO_NEXTCLOUD}\\n\
AUTO_NEXTCLOUD_HSTS=${AUTO_NEXTCLOUD_HSTS}\\n\
AUTO_NEXTCLOUD_NO_ROBOTS=${AUTO_NEXTCLOUD_NO_ROBOTS}\\n"

# Homeassistant
if [ "${AUTO_HOMEASSISTANT}" == "true" ]; then
    HASS_PATH_CONFIG_SAMPLE=/config/nginx/proxy-confs/homeassistant.subdomain.conf.sample
    HASS_PATH_CONFIG=/config/nginx/proxy-confs/homeassistant.subdomain.conf
    cp "$HASS_PATH_CONFIG_SAMPLE" "$HASS_PATH_CONFIG"

    echo "Auto enabled Homeassistant proxy-config."

    # adjust endpoint if needed
    if [ ! -z "${AUTO_HOMEASSISTANT_ENDPOINT}" ]; then
        sed -i "s/set \$upstream_app.*/set \$upstream_app $HOMEASSISTANT_ENDPOINT;/" "$HASS_PATH_CONFIG"
        echo "Updated the Homeassistant endpoint.."
    fi
fi

# Nextcloud
if [ "${AUTO_NEXTCLOUD}" == "true" ]; then
    NEXTCLOUD_PATH_CONFIG_SAMPLE=/config/nginx/proxy-confs/nextcloud.subdomain.conf.sample
    NEXTCLOUD_PATH_CONFIG=/config/nginx/proxy-confs/nextcloud.subdomain.conf
    cp "$NEXTCLOUD_PATH_CONFIG_SAMPLE" "$NEXTCLOUD_PATH_CONFIG"

    echo "Auto enabled Nextcloud proxy-config."

    # adjust endpoint if needed
    if [ ! -z "${AUTO_NEXTCLOUD_ENDPOINT}" ]; then
        sed -i "s/set \$upstream_app.*/set \$upstream_app $AUTO_NEXTCLOUD_ENDPOINT;/" "$NEXTCLOUD_PATH_CONFIG"
        echo "Updated the Nextcloud endpoint.."
    fi

    # add hsts tag
    if [ "${AUTO_NEXTCLOUD_HSTS}" == "true" ]; then
        HSTS_TAG="add_header Strict-Transport-Security \"max-age=15552000; includeSubDomains\";"
        sed -i "/server_name nextcloud.*;/a$HSTS_TAG" "$NEXTCLOUD_PATH_CONFIG"
        echo "Added HSTS tag to nextcloud proxy-config.."
    fi

    # add hsts tag
    if [ "${AUTO_NEXTCLOUD_NO_ROBOTS}" == "true" ]; then
        NO_ROBOTS_TAG="add_header X-Robots-Tag \"noindex, nofollow, nosnippet, noarchive\";"
        sed -i "/server_name nextcloud.*;/a$NO_ROBOTS_TAG" "$NEXTCLOUD_PATH_CONFIG"
        echo "Added No Robots tag to nextcloud proxy-config.."
    fi
fi

echo "Done! ENV auto config succeeded."
